[build]
nixpacks.pkgs = []
nixpacks.aptPkgs = []
nixpacks.buildPkgs = []

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[env]
PHP_VERSION = "8.4"
NODE_OPTIONS = "--max-old-space-size=512"
NODE_ENV = "production"
